-- 010_resume_bullets.sql — jobs_tracker_v2
--
--   psql -d jobs_tracker_v2 -v ON_ERROR_STOP=1 -f db/migrations/010_resume_bullets.sql
--
-- ============================================================================
-- ⛔ THIS TABLE IS DERIVED. IT IS NEVER AUTHORED. EDITING A ROW CHANGES NOTHING.
-- ============================================================================
--
-- The source of truth is `<workspace>/upgrad_resume.html`, and it stays the source
-- of truth. `automation/upgrad_apply.py` exports by reading that file; nothing
-- reads this table on the way to Hiration, and nothing here is ever written back
-- to a résumé. The direction is one-way and absolute:
--
--     upgrad_resume.html  ->  resume_bullets  ->  rendered pages / PDF / .docx
--
-- Every row is regenerated by `automation/jobs_sync.py --bullets`, which deletes
-- and reinserts a source wholesale. So:
--
--   * An UPDATE against this table survives until the next sync and then vanishes.
--   * A bullet that is WRONG is fixed in `upgrad_resume.html` and re-synced.
--     Never in the row, and never in a page rendered from the row.
--   * A page built from this table is a VIEW. Same rule: fix the file.
--
-- WHY IT EXISTS. His question, 2026-08-26: "for a given company_slug, what were
-- the bullet points for VoltusWave's Principal Software Architect role? For a
-- different company, what were the bullet points?" That is a comparison across
-- seats, and grep cannot do it — the per-job résumés are gitignored, the same
-- role is a different id in every workspace, and verb collisions hide mid-bullet.
--
-- The precedent is `fit_score`: `score.json` is the source, `jobs_sync.py --scores`
-- re-reads it, the launcher queries the database. Same shape, same direction.
--
-- SECOND PURPOSE, added the same day: rendering. CLAUDE.md already requires
-- "generate copy blocks FROM the résumé, never retype them", because a paste
-- sheet that disagrees with the file the bot writes from is drift. If the
-- renderers read this table, that disagreement stops being a rule someone has to
-- remember and becomes structurally impossible. Hence `html` (bold survives),
-- the role columns (a CV needs dates and a title) and `card_only` (a paste sheet
-- must offer only the ten the bot writes; a Word CV wants all fifteen).
--
-- ⚠ A locally rendered PDF does NOT replace the upGrad/Hiration export. See
-- db/README.md — both paths stay, and they serve different jobs.
--
-- Idempotent: safe to re-run. Creates nothing that exists, drops nothing at all.

\set ON_ERROR_STOP on
BEGIN;

CREATE TABLE IF NOT EXISTS resume_bullets (
    id             serial PRIMARY KEY,

    -- The seat this résumé belongs to. NULL for `source = 'master'`, which has no
    -- seat, and NULL for a workspace on disk that is not registered yet.
    -- CASCADE so deleting a seat cannot leave its bullets behind.
    application_id integer REFERENCES applications(id) ON DELETE CASCADE,

    -- Which résumé this came from: a seat slug, or the literal 'master'.
    source         text NOT NULL,
    -- The file that was parsed, repo-relative. A reader who finds a wrong bullet
    -- needs to know WHICH FILE TO FIX; this column is that answer, and it is the
    -- reason the "fix the file, not the row" rule is actionable from a query.
    source_path    text NOT NULL,
    -- Digest of that file at sync time. Two uses: a workspace whose résumé is
    -- still a byte-identical copy of the master is one query away (same digest),
    -- and a table that has gone stale against the file is detectable.
    source_sha256  text NOT NULL,

    -- The section id in the file — the parser contract in master/README.md.
    -- quick-headline · quick-summary · quick-skills-{tls,ee,bd} ·
    -- quick-{vp,deque,rocket,voltuswave-cofounder,teletext} ·
    -- p-{cura,innroad,mcd,elpaso,lynton}
    section_id     text NOT NULL,
    -- headline | summary | skills | experience. A CHECK rather than an enum: the
    -- vocabulary is `upgrad_resume_paste.SECTION_ORDER`'s to define, and it should
    -- change with the parser in one line, not through a type migration.
    section_kind   text NOT NULL
        CHECK (section_kind IN ('headline', 'summary', 'skills', 'experience')),
    -- The file's own <h2>, leading "N. " stripped, otherwise verbatim.
    section_label  text,
    -- TRUE for the five pre-2016 roles. The exporter never writes them — they are
    -- hand-edited in the Hiration card — but they are on the résumé, and
    -- CLAUDE.md's verb-uniqueness rule counts them.
    card_only      boolean NOT NULL DEFAULT false,

    -- Resolved from the résumé's OWN dates table, positionally: the Nth
    -- experience section is row N. This is what makes section_id='quick-vp' read
    -- back as "VoltusWave Technologies — Principal Software Architect", which is
    -- how he asked the question. NULL on non-experience sections.
    --
    -- ⚠ date_from/date_to are what the FILE asserts. The dates on an exported PDF
    -- live in the Hiration card. For a locally rendered CV this is the only date
    -- source there is, which is exactly why they are here.
    company        text,
    role_title     text,
    date_from      text,
    date_to        text,
    location       text,

    -- 1-based position within the section, in file order.
    ord            integer NOT NULL CHECK (ord >= 1),

    -- The bullet, tags stripped and entities unescaped. Plain-text renderers and
    -- the Naukri-safe transform (its Job-profile textarea rejects `<` and `\`)
    -- read this one.
    text           text NOT NULL,
    -- The bullet's inner HTML, so <strong> survives. LOAD-BEARING: upGrad strips
    -- bold from list-rooted content and a hand-dragged selection loses it, so a
    -- renderer that only had `text` would silently ship an unbolded résumé.
    html           text NOT NULL,

    -- Hygiene, computed once at sync from CLAUDE.md's per-bullet rules.
    -- leading_verb is NULL off the experience sections: "unique leading verb" is
    -- a rule about experience bullets, and a NULL keeps a naive verb query from
    -- counting "Technology" out of the skills block as a leading verb.
    leading_verb   text,
    word_count     integer NOT NULL,
    has_bold       boolean NOT NULL,
    -- Mechanical proxy only: a digit or a `%`. CLAUDE.md's rule is "a number, %,
    -- scale marker, or measurable outcome" and the last two are human judgement.
    -- A FALSE here is a real miss; a TRUE is "worth a look", not a pass.
    has_number     boolean NOT NULL,

    synced_at      timestamptz NOT NULL DEFAULT now(),

    -- The natural key. Also the guard that a re-sync cannot double a section.
    CONSTRAINT resume_bullets_source_section_ord UNIQUE (source, section_id, ord)
);

-- "The same role across every seat, side by side" is the query he asked for.
CREATE INDEX IF NOT EXISTS resume_bullets_section_source
    ON resume_bullets (section_id, source);
CREATE INDEX IF NOT EXISTS resume_bullets_source
    ON resume_bullets (source);
-- Verb collisions across seats, which is the check grep cannot do cleanly.
CREATE INDEX IF NOT EXISTS resume_bullets_leading_verb
    ON resume_bullets (leading_verb) WHERE leading_verb IS NOT NULL;

COMMENT ON TABLE resume_bullets IS
    'DERIVED index over every upgrad_resume.html, regenerated by jobs_sync.py --bullets. '
    'The files are the source of truth; editing a row here changes nothing about what '
    'the exporter writes, and is overwritten by the next sync. Fix the résumé, re-sync.';
COMMENT ON COLUMN resume_bullets.html IS
    'Inner HTML with <strong> intact. A renderer must use this, not `text`: upGrad '
    'strips bold from list-rooted content and a hand-dragged copy loses it entirely.';
COMMENT ON COLUMN resume_bullets.source_path IS
    'The file to fix when a bullet is wrong. Never edit the row or a rendered page.';
COMMENT ON COLUMN resume_bullets.has_number IS
    'Mechanical proxy: a digit or a %. "Scale marker or measurable outcome" is human judgement.';

-- ---------------------------------------------------------------------------
-- Prove the shape, or refuse to commit.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  n_cols    bigint;
  n_uniq    bigint;
  n_fk      bigint;
  n_idx     bigint;
  n_notnull bigint;
BEGIN
  SELECT count(*) INTO n_cols FROM information_schema.columns
   WHERE table_schema = 'public' AND table_name = 'resume_bullets';
  SELECT count(*) INTO n_uniq FROM pg_constraint
   WHERE conname = 'resume_bullets_source_section_ord' AND contype = 'u';
  SELECT count(*) INTO n_fk FROM pg_constraint
   WHERE conrelid = 'resume_bullets'::regclass AND contype = 'f'
     AND confrelid = 'applications'::regclass AND confdeltype = 'c';
  SELECT count(*) INTO n_idx FROM pg_indexes
   WHERE tablename = 'resume_bullets'
     AND indexname IN ('resume_bullets_section_source', 'resume_bullets_source',
                       'resume_bullets_leading_verb');
  -- application_id must stay NULLable: 'master' has no seat, and a workspace can
  -- exist on disk before it is registered. A NOT NULL here would make the sync
  -- either skip those or invent a row in `applications`, and both are worse.
  SELECT count(*) INTO n_notnull FROM information_schema.columns
   WHERE table_name = 'resume_bullets' AND column_name = 'application_id'
     AND is_nullable = 'YES';

  IF n_cols <> 22 THEN
    RAISE EXCEPTION 'resume_bullets should have 22 columns, found %', n_cols;
  END IF;
  IF n_uniq <> 1 THEN
    RAISE EXCEPTION 'the (source, section_id, ord) unique key is missing — a re-sync could double a section';
  END IF;
  IF n_fk <> 1 THEN
    RAISE EXCEPTION 'the application_id -> applications(id) ON DELETE CASCADE foreign key is missing';
  END IF;
  IF n_idx <> 3 THEN
    RAISE EXCEPTION 'expected 3 indexes, found %', n_idx;
  END IF;
  IF n_notnull <> 1 THEN
    RAISE EXCEPTION 'application_id must stay nullable — master has no seat';
  END IF;

  RAISE NOTICE 'OK — resume_bullets ready (derived; populate with jobs_sync.py --bullets)';
END $$;

COMMIT;
