-- db/operations/apply_story_clusters.sql
--
-- The story-cluster DRAFT of the résumé (28 Sep 2026): every experience bullet re-told as
-- problem, then decisions, then outcome, plus a problem-first headline and summary. It
-- writes ONLY the variant 'variant:story-clusters'; the master is never touched.
-- Generated from the adjudicated drafts of workflow run wf_3971e59d-a9c (PENDING.md).
--
--   psql -d jobs_tracker_v2 -v ON_ERROR_STOP=1 -c "select set_config('variant.name','story-clusters',false)" \
--        -f db/operations/clone_master_variant.sql            # once
--   psql -d jobs_tracker_v2 -v ON_ERROR_STOP=1 -f db/operations/apply_story_clusters.sql   # re-runnable
--
-- Re-runnable: it deletes the variant's blocks in the sections it rewrites and inserts the
-- draft again. Skills sections are not rewritten.

\set ON_ERROR_STOP on
BEGIN;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM resume_documents WHERE doc_key = 'variant:story-clusters') THEN
        RAISE EXCEPTION 'no variant:story-clusters -- run clone_master_variant.sql with variant.name story-clusters first';
    END IF;
END $$;

DELETE FROM resume_blocks
 WHERE doc_key = 'variant:story-clusters'
   AND section_id IN ('p-cura', 'p-elpaso', 'p-innroad', 'p-lynton', 'p-mcd', 'quick-deque', 'quick-headline', 'quick-rocket', 'quick-summary', 'quick-teletext', 'quick-voltuswave-cofounder', 'quick-vp');

INSERT INTO resume_blocks (doc_key, section_id, section_kind, ord, bullet_key, html) VALUES
  ('variant:story-clusters', 'quick-headline', 'headline', 1, 'story:headline', $h$Hands-on Principal Architect · 19+ yrs · Problem-first production AI: RAG, multi-agent, LLM · Java + Spring Boot (11 yrs) · Multi-tenant SaaS · AWS, Kubernetes, Terraform · Graph + GNN · HIPAA, ISO 27001 · AI-Leveraged Delivery (Claude Code + OpenAI Codex)$h$),
  ('variant:story-clusters', 'quick-summary', 'summary', 1, 'story:summary', $h$Hands-on principal architect, <strong>19+ years</strong>, who starts from the business problem and designs back to the architecture. Strongest in <strong>Java and Spring Boot</strong>: about <strong>11 years of Java across three eras</strong>, from server-side Java in 2008 to <strong>Spring Boot 2.x on Java 8/17</strong> through February 2025. At Deque, every customer ran its own instance, so each upgrade and onboarding was repeated per customer; consolidated per-customer deployments onto shared <strong>multi-tenant</strong> software as a service (SaaS) infrastructure, with dedicated isolation for regulated banking customers. At VoltusWave, a chronic-care client needed artificial intelligence (AI) in its product to raise investment, which first needed patients on a reliable chat platform: rewrote its core chat service from <strong>Node.js to Go</strong> behind a two-stream <strong>Amazon Kinesis</strong> design, multi-availability-zone with failover and disaster recovery for <strong>Health Insurance Portability and Accountability Act (HIPAA)</strong> compliance. Then built ten analytics and AI services on Amazon Web Services (AWS), all in production: retrieval-augmented generation (RAG) precedent search for clinicians, a multi-agent orchestrator, causal inference and leakage-safe machine learning over <strong>9–10 years of patient history</strong>, and self-hosted <strong>large language models (LLMs)</strong> inside the client boundary, where code computes every number and a model only narrates; alongside them, a <strong>graph neural network (GNN)</strong> context graph. Standardised the organisation on <strong>Kubernetes and Terraform</strong>, cutting infrastructure cost <strong>25–30%</strong> and deploy time to <strong>under 10 minutes</strong>.$h$),
  ('variant:story-clusters', 'quick-vp', 'experience', 1, 'story:quick-vp:1', $h$Distilled the client's goal of raising investment on artificial intelligence (AI) into <strong>10 killer queries</strong>, agreed with its chief executive, proving the AI was real$h$),
  ('variant:story-clusters', 'quick-vp', 'experience', 2, 'story:quick-vp:2', $h$Pioneered a <strong>Context Graph on Amazon Neptune</strong> with graph neural network (GNN) models across 80+ chronic conditions, projected from an event-sourced DynamoDB single-table spine$h$),
  ('variant:story-clusters', 'quick-vp', 'experience', 3, 'story:quick-vp:3', $h$Delivered <strong>10 decision-intelligence services</strong> on 4 query archetypes to production for ~10,000 patients, absorbing 20 review findings into one design$h$),
  ('variant:story-clusters', 'quick-vp', 'experience', 4, 'story:quick-vp:4', $h$Engineered retrieval-augmented generation (RAG) for clinical precedent search across <strong>80+ chronic conditions</strong>, because a database filter returns a cohort, not the most analogous decisions$h$),
  ('variant:story-clusters', 'quick-vp', 'experience', 5, 'story:quick-vp:5', $h$Optimised retrieval around the decision, not the patient, via tenant-filtered <strong>Elasticsearch dense_vector</strong> nearest-neighbour search, tuned to a 0.75 normalised discounted cumulative gain target$h$),
  ('variant:story-clusters', 'quick-vp', 'experience', 6, 'story:quick-vp:6', $h$Launched the precedent panel <strong>in production</strong> for doctors, health coaches and guidance counsellors, answering cases short of 7 required fields with a plain cohort count$h$),
  ('variant:story-clusters', 'quick-vp', 'experience', 7, 'story:quick-vp:7', $h$Conceived a <strong>multi-agent orchestrator</strong> showing which care decisions followed when a patient's payments, adherence and support broke inside one 90-day window$h$),
  ('variant:story-clusters', 'quick-vp', 'experience', 8, 'story:quick-vp:8', $h$Developed orchestration as a deterministic LangGraph state graph: <strong>3 blind finder agents</strong> run in parallel; a barrier re-verifies every proposed patient against a frozen snapshot$h$),
  ('variant:story-clusters', 'quick-vp', 'experience', 9, 'story:quick-vp:9', $h$Shipped the orchestrator to production behind <strong>executive and operations dashboards</strong> and audited per-patient drill-ins, suppressing any delta failing a 0.10 balance gate$h$),
  ('variant:story-clusters', 'quick-vp', 'experience', 10, 'story:quick-vp:10', $h$Secured protected health information inside the client virtual private cloud, self-hosting <strong>Llama 3.1</strong> on Ollama, embeddings and LangSmith tracing so patient data never left$h$),
  ('variant:story-clusters', 'quick-vp', 'experience', 11, 'story:quick-vp:11', $h$Restricted large language models (LLMs) to narrating code-computed numbers — pinned model, temperature 0, chain hash, field-level claim grammar — designed to reject <strong>100% of uncited claims</strong>$h$),
  ('variant:story-clusters', 'quick-vp', 'experience', 12, 'story:quick-vp:12', $h$Instituted confounder-gated cohort comparisons, since clinicians override on their sickest patients, making any headline failing a <strong>0.1 standardised mean difference</strong> balance check unrepresentable$h$),
  ('variant:story-clusters', 'quick-vp', 'experience', 13, 'story:quick-vp:13', $h$Strengthened statistical rigour across <strong>6 production pipelines</strong> with propensity matching, B=2000 bootstrap resamples and a Rosenbaum γ plus E-value sensitivity battery, feeding governed dashboards$h$),
  ('variant:story-clusters', 'quick-vp', 'experience', 14, 'story:quick-vp:14', $h$Transformed patient event histories into a relapse early-warning model on <strong>Amazon SageMaker</strong>, since relapse, at a 5–15% base rate, shows in event order, not counts$h$),
  ('variant:story-clusters', 'quick-vp', 'experience', 15, 'story:quick-vp:15', $h$Gated the model on <strong>6-month</strong> matured outcome labels, then rolled it out to health coaches under per-coach daily alert budgets and an owned alert lifecycle$h$),
  ('variant:story-clusters', 'quick-vp', 'experience', 16, 'story:quick-vp:16', $h$Enforced multi-tenant isolation under a Health Insurance Portability and Accountability Act (HIPAA) framework across <strong>10 production pipelines</strong> — tenant-scoped traversal-source wrapper, Parquet partitioning, runtime assertions$h$),
  ('variant:story-clusters', 'quick-vp', 'experience', 17, 'story:quick-vp:17', $h$Deployed Datadog observability since nobody knew why the chat platform was unreliable, cutting errors to <strong>under 3%</strong> and revealing ~50 downstream calls per patient message$h$),
  ('variant:story-clusters', 'quick-vp', 'experience', 18, 'story:quick-vp:18', $h$Spearheaded the chat service rewrite from Node.js to Go, reaching <strong>100,000 concurrent connections</strong> at P95 under 16 ms in k6-validated burst testing$h$),
  ('variant:story-clusters', 'quick-vp', 'experience', 19, 'story:quick-vp:19', $h$Architected a two-stream <strong>Amazon Kinesis</strong> design with Enhanced Fan-Out, expanding 4 to 1,200 shards, as production headroom against spikes beyond the burst test$h$),
  ('variant:story-clusters', 'quick-vp', 'experience', 20, 'story:quick-vp:20', $h$Reimagined the data layer across DynamoDB, PostgreSQL and OpenSearch with partition-key and indexing design holding <strong>P95 under 30 ms</strong> at 100,000-user load$h$),
  ('variant:story-clusters', 'quick-vp', 'experience', 21, 'story:quick-vp:21', $h$Published React Native apps to 2 app stores with Firebase Cloud Messaging and Apple Push Notification service (APNs), moving <strong>10,000+ patients</strong> off third-party messaging$h$),
  ('variant:story-clusters', 'quick-vp', 'experience', 22, 'story:quick-vp:22', $h$Recruited engineering from <strong>0 to 20+</strong> across 6 sub-teams — backend, React Native, web, artificial intelligence, quality assurance (QA), DevOps — standardised on Go and DynamoDB$h$),
  ('variant:story-clusters', 'quick-vp', 'experience', 23, 'story:quick-vp:23', $h$Drove a Claude Code and OpenAI Codex rollout across a <strong>20-engineer team</strong> — daily design exploration, first-cut implementation and test scaffolding, all under hands-on review$h$),
  ('variant:story-clusters', 'quick-vp', 'experience', 24, 'story:quick-vp:24', $h$Provisioned Amazon Web Services on Kubernetes, Terraform and Elastic Container Service Fargate at 70% Spot — deploys <strong>under 10 minutes</strong>, infrastructure cost down 25–30%$h$),
  ('variant:story-clusters', 'quick-deque', 'experience', 1, 'story:quick-deque:1', $h$Reframed axe Monitor's bottleneck as deployment, not product: <strong>280 clients</strong>, each on its own instance, version and Keycloak, so every upgrade and trial multiplied$h$),
  ('variant:story-clusters', 'quick-deque', 'experience', 2, 'story:quick-deque:2', $h$Implemented multi-tenancy as an organisation identifier on every table, resolving tenant from the JSON Web Token (JWT) into <strong>1 code path</strong>, not database-per-customer$h$),
  ('variant:story-clusters', 'quick-deque', 'experience', 3, 'story:quick-deque:3', $h$Steered 70–80% of customers onto shared axe Monitor instances on <strong>Spring Boot 2.x and Java 8/17</strong>, one codebase also serving regulated banks on dedicated databases$h$),
  ('variant:story-clusters', 'quick-deque', 'experience', 4, 'story:quick-deque:4', $h$Exposed shared platform application programming interfaces (APIs) to <strong>280 axe Monitor clients</strong> — Jira integration, API versioning, customer-specific frontends on one Spring Boot backend, backward compatibility$h$),
  ('variant:story-clusters', 'quick-deque', 'experience', 5, 'story:quick-deque:5', $h$Championed decomposition of a monolith into <strong>10–15 services</strong>, splitting only where a component needed independent scaling or its own multi-tenant database$h$),
  ('variant:story-clusters', 'quick-deque', 'experience', 6, 'story:quick-deque:6', $h$Productized a billing and subscription service for <strong>every Deque product</strong>, restricting features by tier, porting it from Node.js/TypeScript to Java and Spring Boot$h$),
  ('variant:story-clusters', 'quick-deque', 'experience', 7, 'story:quick-deque:7', $h$Forged central authentication in Java and Spring Boot on OAuth 2.0, folding every instance's local Keycloak into Red Hat single sign-on with <strong>zero end-user disruption</strong>$h$),
  ('variant:story-clusters', 'quick-deque', 'experience', 8, 'story:quick-deque:8', $h$Stewarded every axe Auditor instance from PostgreSQL 9.6, bundled in its Docker Compose stack, to Amazon Aurora PostgreSQL 13.x with <strong>zero downtime</strong>$h$),
  ('variant:story-clusters', 'quick-deque', 'experience', 9, 'story:quick-deque:9', $h$Trimmed daily backup windows <strong>3–4 hours</strong> and deploy errors 40% by moving PostgreSQL onto Amazon Relational Database Service (RDS)$h$),
  ('variant:story-clusters', 'quick-deque', 'experience', 10, 'story:quick-deque:10', $h$Modernised continuous integration and continuous delivery (CI/CD) from Jenkins to GitHub Actions, achieving ISO 27001 and <strong>50% faster</strong> release cycles$h$),
  ('variant:story-clusters', 'quick-deque', 'experience', 11, 'story:quick-deque:11', $h$Slashed regression testing time <strong>over 50%</strong> with an end-to-end automated testing framework built on Puppeteer$h$),
  ('variant:story-clusters', 'quick-deque', 'experience', 12, 'story:quick-deque:12', $h$Tackled accessibility teams' blind spot, unknown page counts and unannounced uniform resource locator (URL) changes, with spider discovery <strong>1 to 5 levels deep, or all</strong>$h$),
  ('variant:story-clusters', 'quick-deque', 'experience', 13, 'story:quick-deque:13', $h$Orchestrated spider jobs and scheduled axe-core scans for <strong>280 axe Monitor clients</strong>, comparing each run with the last to flag new, fixed and regressed pages$h$),
  ('variant:story-clusters', 'quick-deque', 'experience', 14, 'story:quick-deque:14', $h$Constructed comparable test runs in the axe DevTools browser extension, running axe-core on <strong>every page and user action</strong> in a flow, de-duplicating issues server-side$h$),
  ('variant:story-clusters', 'quick-deque', 'experience', 15, 'story:quick-deque:15', $h$Broadened axe DevTools scanning into cross-origin iframes, which the browser's security model hid and where the extension reported <strong>zero issues</strong>, landing phase 1$h$),
  ('variant:story-clusters', 'quick-rocket', 'experience', 1, 'story:quick-rocket:1', $h$Anchored decomposition of the <strong>IBM Db2 Configuration Manager</strong> monolith into Java and Spring Boot microservices, defining boundaries across z/OS mainframe and distributed platforms$h$),
  ('variant:story-clusters', 'quick-rocket', 'experience', 2, 'story:quick-rocket:2', $h$Surfaced defect hot-spots by isolating services behind representational state transfer (REST) interfaces, reducing reported bugs <strong>over 50%</strong>$h$),
  ('variant:story-clusters', 'quick-rocket', 'experience', 3, 'story:quick-rocket:3', $h$Partnered with product to extend platform support to Windows and three Linux distributions — Ubuntu, CentOS, Red Hat Enterprise Linux (RHEL) — raising sales <strong>over 20%</strong>$h$),
  ('variant:story-clusters', 'quick-rocket', 'experience', 4, 'story:quick-rocket:4', $h$Coached a <strong>5-engineer</strong> team through delivery planning, code review and performance appraisals, remaining hands-on as an individual-contributor Software Engineer III$h$),
  ('variant:story-clusters', 'quick-voltuswave-cofounder', 'experience', 1, 'story:quick-voltuswave-cofounder:1', $h$Co-founded VoltusWave and released its first no-code application Platform-as-a-Service (aPaaS) for web and Android on Amazon Elastic Container Service, winning <strong>8 early enterprise clients</strong>$h$),
  ('variant:story-clusters', 'quick-voltuswave-cofounder', 'experience', 2, 'story:quick-voltuswave-cofounder:2', $h$Mobilized an engineering organisation from <strong>0 to 35</strong> in 13 months, mentoring freshers and seniors and setting the architectural roadmap later products followed$h$),
  ('variant:story-clusters', 'quick-teletext', 'experience', 1, 'story:quick-teletext:1', $h$Codified a MuleSoft enterprise service bus scatter-gather giving sales reps <strong>25 suppliers' rates</strong> in parallel, superseding .NET 2.0 code a prior team could not upgrade$h$),
  ('variant:story-clusters', 'quick-teletext', 'experience', 2, 'story:quick-teletext:2', $h$Retired a third-party hotel pricing search whose load-based billing grew with <strong>2–3 million daily requests</strong> at peak, calling suppliers directly instead$h$),
  ('variant:story-clusters', 'quick-teletext', 'experience', 3, 'story:quick-teletext:3', $h$Cached airport-destination-date queries on in-house Elasticsearch, Logstash and Kibana (ELK) with a 20-minute time-to-live, suppliers called only on a miss, lowering operational cost <strong>46%</strong>$h$),
  ('variant:story-clusters', 'quick-teletext', 'experience', 4, 'story:quick-teletext:4', $h$Traced hidden hotel inventory to clashing identifiers across 25 suppliers, where unmapped properties lacked images and ratings, and adopted licensed <strong>GIATA MultiCodes</strong>$h$),
  ('variant:story-clusters', 'quick-teletext', 'experience', 5, 'story:quick-teletext:5', $h$Mechanised the reconciliation pipeline on Amazon Web Services (AWS) Lambda with human approval retained, growing revenue <strong>8% month over month</strong>$h$),
  ('variant:story-clusters', 'quick-teletext', 'experience', 6, 'story:quick-teletext:6', $h$Lifted hotel booking conversions <strong>65%</strong> by widening matched inventory and ranking direct-contract properties first across 2–3 million daily requests at peak$h$),
  ('variant:story-clusters', 'p-cura', 'experience', 1, 'story:p-cura:1', $h$Pinpointed <strong>2 paid Microsoft licences</strong>, Windows Server and SQL Server, as the biggest customer cost objection to a Governance, Risk and Compliance (GRC) platform$h$),
  ('variant:story-clusters', 'p-cura', 'experience', 2, 'story:p-cura:2', $h$Recast the SQL Server data model as MySQL on Ubuntu and Node.js, a <strong>2nd supported stack</strong> for new enterprise accounts only, leaving Windows customers untouched$h$),
  ('variant:story-clusters', 'p-cura', 'experience', 3, 'story:p-cura:3', $h$Unlocked <strong>12 new enterprise customers</strong> in two months, October and November 2015, on the licence-free Linux deployment$h$),
  ('variant:story-clusters', 'p-innroad', 'experience', 1, 'story:p-innroad:1', $h$Replatformed a server-rendered ASP.NET application into an AngularJS single-page application (SPA) over .NET Windows Communication Foundation (WCF) services, <strong>splitting 1 app into 2 tiers</strong>$h$),
  ('variant:story-clusters', 'p-innroad', 'experience', 2, 'story:p-innroad:2', $h$Calibrated the data layer on <strong>3 fronts</strong>, stored procedures, table design and indexing, clearing the query bottlenecks behind slow screen loads$h$),
  ('variant:story-clusters', 'p-innroad', 'experience', 3, 'story:p-innroad:3', $h$Shortened screen load times <strong>60–70%</strong> once the single-page client and tuned queries replaced server-rendered pages$h$),
  ('variant:story-clusters', 'p-mcd', 'experience', 1, 'story:p-mcd:1', $h$Unified employee records from every store for leadership in a <strong>2-country</strong> Master Data Management (MDM) pilot, United States and Canada, on SQL Server$h$),
  ('variant:story-clusters', 'p-mcd', 'experience', 2, 'story:p-mcd:2', $h$Salvaged the unusable built-in MDM interface with a rebuilt front end, adding <strong>first seen and last updated</strong> timestamps per field on every master record$h$),
  ('variant:story-clusters', 'p-elpaso', 'experience', 1, 'story:p-elpaso:1', $h$Translated a Citrix-hosted Java application into JavaServer Pages (JSP) and Java Enterprise Edition for Tennessee Gas Pipeline, an <strong>11,800-mile</strong> interstate system$h$),
  ('variant:story-clusters', 'p-elpaso', 'experience', 2, 'story:p-elpaso:2', $h$Authored <strong>3 core modules</strong> — Nominations, Flowing Gas and Contracts — covering scheduling and contracting for interstate gas transport over 4 years$h$),
  ('variant:story-clusters', 'p-elpaso', 'experience', 3, 'story:p-elpaso:3', $h$Refactored the scheduling modules' schema and stored procedures through a <strong>SQL Server 2000 to 2005</strong> migration, owning table and index design and query tuning$h$),
  ('variant:story-clusters', 'p-lynton', 'experience', 1, 'story:p-lynton:1', $h$Bridged suppliers and buyers through a .NET portal on SQL Server 2005, integrating <strong>Mexican PayPal</strong> to settle payments inside the portal$h$),
  ('variant:story-clusters', 'p-lynton', 'experience', 2, 'story:p-lynton:2', $h$Seeded portal adoption with a Windows service sweeping <strong>every invoice</strong> from a watched folder to the server, built to move everyone onto the portal$h$);

COMMIT;
