-- Adjudicated résumé edits for seat:eli-lilly-sr-principal-engineer-ai-ml-integration (29 Sep 2026); each UPDATE matches the master text, so a re-run changes nothing.
\set ON_ERROR_STOP on
BEGIN;
UPDATE resume_blocks SET html = $h$Engineered a retrieval-augmented generation (RAG) pipeline on <strong>Elasticsearch dense_vector</strong> semantic search across <strong>80+ chronic conditions</strong>, keeping <strong>Amazon Neptune</strong> off the serving path$h$ WHERE doc_key = 'seat:eli-lilly-sr-principal-engineer-ai-ml-integration' AND section_id = 'quick-vp' AND ord = 7 AND retired_at IS NULL AND text = $o$Engineered a retrieval-augmented generation (RAG) pipeline on Elasticsearch dense_vector filtered nearest-neighbour search across 80+ chronic conditions, keeping Amazon Neptune off the serving path$o$;
UPDATE resume_blocks SET html = $h$Tuned precedent retrieval with self-hosted <strong>Amazon SageMaker</strong> embedders, <strong>LangSmith</strong> tracing and an offline evaluation harness, designed against <strong>0.75 normalised discounted cumulative gain</strong>$h$ WHERE doc_key = 'seat:eli-lilly-sr-principal-engineer-ai-ml-integration' AND section_id = 'quick-vp' AND ord = 8 AND retired_at IS NULL AND text = $o$Tuned precedent retrieval on Elasticsearch dense_vector search with self-hosted Amazon SageMaker embedders, designed against warm-path P99 under 200 ms and 0.75 normalised discounted cumulative gain$o$;
UPDATE resume_blocks SET html = $h$Assembled a <strong>10-query</strong> decision-intelligence platform in <strong>Python and FastAPI</strong> on <strong>4 reusable archetypes</strong>, including a deterministic <strong>multi-agent LangGraph</strong> workflow with <strong>3 parallel finder agents</strong>$h$ WHERE doc_key = 'seat:eli-lilly-sr-principal-engineer-ai-ml-integration' AND section_id = 'quick-vp' AND ord = 10 AND retired_at IS NULL AND text = $o$Assembled a 10-query decision-intelligence platform on 4 reusable archetypes — Retrieval, Cohort Aggregation, Sequence Mining, Graph Traversal — on Amazon Neptune$o$;
UPDATE resume_blocks SET html = $h$Instituted event sourcing on <strong>DynamoDB single-table</strong> design, hydrating <strong>9–10 years</strong> of patient history through quarantine-first data-quality gates and deterministic Parquet snapshots$h$ WHERE doc_key = 'seat:eli-lilly-sr-principal-engineer-ai-ml-integration' AND section_id = 'quick-vp' AND ord = 11 AND retired_at IS NULL AND text = $o$Instituted event sourcing on DynamoDB single-table design with a deterministic Parquet snapshot exporter and correction-event backbone, targeting P95 under 5 minutes for dependency-targeted slice rebuilds$o$;
UPDATE resume_blocks SET html = $h$Secured protected health information inside the client <strong>virtual private cloud</strong> by self-hosting embeddings and <strong>Llama 3.1 (8-billion-parameter workhorse, 70-billion escalation)</strong> for every model call$h$ WHERE doc_key = 'seat:eli-lilly-sr-principal-engineer-ai-ml-integration' AND section_id = 'quick-vp' AND ord = 13 AND retired_at IS NULL AND text = $o$Secured protected health information inside the client virtual private cloud by self-hosting embeddings and Llama 3.1 for every model call$o$;
UPDATE resume_blocks SET html = $h$Hardened <strong>10 production analytics services</strong> through structured adversarial self-review, absorbing <strong>twenty findings</strong> into one revision and promoting cross-cutting fixes into shared platform components$h$ WHERE doc_key = 'seat:eli-lilly-sr-principal-engineer-ai-ml-integration' AND section_id = 'quick-vp' AND ord = 16 AND retired_at IS NULL AND text = $o$Hardened ten production analytics services through structured adversarial self-review, absorbing twenty findings into one design and holding another dark until its upstream contract shipped$o$;
UPDATE resume_blocks SET html = $h$Distilled patient event histories into a relapse early-warning model on <strong>Amazon SageMaker</strong>, with nightly batch scoring, drift-triggered retraining and a <strong>6-month</strong> label-maturity gate$h$ WHERE doc_key = 'seat:eli-lilly-sr-principal-engineer-ai-ml-integration' AND section_id = 'quick-vp' AND ord = 19 AND retired_at IS NULL AND text = $o$Distilled patient event histories into a relapse early-warning model on Amazon SageMaker, gated by a 6-month maturity window never to train on immature outcome labels$o$;
UPDATE resume_blocks SET html = $h$Forged central identity in <strong>Spring Boot</strong>, moving every instance from <strong>Keycloak</strong> to <strong>Red Hat single sign-on</strong> over <strong>OpenID Connect and OAuth 2.0</strong>, zero disruption$h$ WHERE doc_key = 'seat:eli-lilly-sr-principal-engineer-ai-ml-integration' AND section_id = 'quick-deque' AND ord = 3 AND retired_at IS NULL AND text = $o$Forged central authentication in Java and Spring Boot, migrating every instance from Keycloak to Red Hat single sign-on — users, roles, client registrations, groups, zero disruption$o$;
UPDATE resume_blocks SET html = $h$Championed decomposition of a monolith into <strong>10–15 microservices</strong>, splitting on independent scaling and database ownership rather than on team boundaries$h$ WHERE doc_key = 'seat:eli-lilly-sr-principal-engineer-ai-ml-integration' AND section_id = 'quick-deque' AND ord = 7 AND retired_at IS NULL AND text = $o$Championed decomposition of a monolith into 10–15 services, splitting on independent scaling and database ownership rather than on team boundaries$o$;
UPDATE resume_blocks SET html = $h$Codified parallel scatter-gather integration across <strong>25 hotel supplier APIs</strong> on a <strong>MuleSoft enterprise service bus</strong>, superseding <strong>.NET 2.0</strong> a prior team could not upgrade$h$ WHERE doc_key = 'seat:eli-lilly-sr-principal-engineer-ai-ml-integration' AND section_id = 'quick-teletext' AND ord = 1 AND retired_at IS NULL AND text = $o$Codified a parallel scatter-gather across 25 hotel suppliers on a MuleSoft enterprise service bus, superseding a .NET 2.0 stack a prior team could not upgrade$o$;
UPDATE resume_blocks SET html = $h$Reconciled per-supplier hotel identifiers onto licensed <strong>GIATA MultiCodes</strong>, automating the pipeline on <strong>AWS Lambda</strong> with human-in-the-loop approval retained, growing revenue <strong>8% month over month</strong>$h$ WHERE doc_key = 'seat:eli-lilly-sr-principal-engineer-ai-ml-integration' AND section_id = 'quick-teletext' AND ord = 3 AND retired_at IS NULL AND text = $o$Reconciled per-supplier hotel identifiers onto licensed GIATA MultiCodes, automating the pipeline on AWS Lambda with human approval retained, growing revenue 8% month over month$o$;
COMMIT;
