-- Adjudicated résumé edits for seat:astroum-ai-principal-lead-software-engineer (2 Oct 2026): 6 of 8 kept; vp-03 cut (its review was of the offline work sample, and the bullet implied it preceded launch), cofounder-01 cut ('delivered' collides with quick-vp 3; journey 472 still asks what he built himself); vp-02 loses 'clinician-graded' (open since Tachyon). Each UPDATE matches the master text, so a re-run changes nothing.
\set ON_ERROR_STOP on
BEGIN;
UPDATE resume_blocks SET html = $h$Engineered retrieval-augmented generation (RAG) for clinical precedent search with <strong>0 LLM calls in ranking</strong>, a two-tier <strong>Redis</strong> cache and a <strong>1.5-second</strong> circuit breaker$h$ WHERE doc_key = 'seat:astroum-ai-principal-lead-software-engineer' AND section_id = 'quick-vp' AND ord = 4 AND retired_at IS NULL AND text = $o$Engineered retrieval-augmented generation (RAG) for clinical precedent search across 80+ chronic conditions, because a database filter returns a cohort, not the most analogous decisions$o$;
UPDATE resume_blocks SET html = $h$Optimised <strong>dense_vector</strong> retrieval on Elasticsearch against an offline <strong>evaluation harness</strong> built to a <strong>100+ query</strong> golden-set contract, targeting <strong>0.75</strong> normalised discounted cumulative gain$h$ WHERE doc_key = 'seat:astroum-ai-principal-lead-software-engineer' AND section_id = 'quick-vp' AND ord = 5 AND retired_at IS NULL AND text = $o$Optimised retrieval around the decision, not the patient, via tenant-filtered Elasticsearch dense_vector nearest-neighbour search, tuned to a 0.75 normalised discounted cumulative gain target$o$;
UPDATE resume_blocks SET html = $h$Secured <strong>protected health information</strong> inside the client virtual private cloud, self-hosting <strong>Llama 3.1 8B with 70B escalation</strong> on Ollama, embeddings and LangSmith tracing$h$ WHERE doc_key = 'seat:astroum-ai-principal-lead-software-engineer' AND section_id = 'quick-vp' AND ord = 10 AND retired_at IS NULL AND text = $o$Secured protected health information inside the client virtual private cloud, self-hosting Llama 3.1 on Ollama, embeddings and LangSmith tracing so patient data never left$o$;
UPDATE resume_blocks SET html = $h$Strengthened data quality over <strong>9–10 years of patient history</strong> with idempotent, resumable loads, unmappable rows quarantined with a reason, and <strong>snapshot-hash version pins</strong>$h$ WHERE doc_key = 'seat:astroum-ai-principal-lead-software-engineer' AND section_id = 'quick-vp' AND ord = 13 AND retired_at IS NULL AND text = $o$Strengthened statistical rigour across 6 production pipelines with propensity matching, B=2000 bootstrap resamples and a Rosenbaum γ plus E-value sensitivity battery, feeding governed dashboards$o$;
UPDATE resume_blocks SET html = $h$Enforced multi-tenant isolation under a Health Insurance Portability and Accountability Act (HIPAA) framework across <strong>10 production pipelines</strong> — role-based access control, audit trails, runtime tenant assertions$h$ WHERE doc_key = 'seat:astroum-ai-principal-lead-software-engineer' AND section_id = 'quick-vp' AND ord = 16 AND retired_at IS NULL AND text = $o$Enforced multi-tenant isolation under a Health Insurance Portability and Accountability Act (HIPAA) framework across 10 production pipelines — tenant-scoped traversal-source wrapper, Parquet partitioning, runtime assertions$o$;
UPDATE resume_blocks SET html = $h$Drove <strong>Claude Code and OpenAI Codex</strong> adoption across a <strong>20-engineer</strong> team: first-cut implementations and test scaffolding under hands-on review, CLAUDE.md and AGENTS.md standards$h$ WHERE doc_key = 'seat:astroum-ai-principal-lead-software-engineer' AND section_id = 'quick-vp' AND ord = 23 AND retired_at IS NULL AND text = $o$Drove a Claude Code and OpenAI Codex rollout across a 20-engineer team, codifying repository standards in CLAUDE.md and AGENTS.md files to shorten onboarding$o$;
COMMIT;
