-- Adjudicated résumé edits for seat:zenvyra-technical-co-founder (29 Sep 2026); each UPDATE matches the master text, so a re-run changes nothing.
\set ON_ERROR_STOP on
BEGIN;
UPDATE resume_blocks SET html = $h$Delivered <strong>10 decision-intelligence services</strong> in Python and FastAPI on 4 query archetypes to production for ~10,000 patients, absorbing 20 review findings into one design$h$ WHERE doc_key = 'seat:zenvyra-technical-co-founder' AND section_id = 'quick-vp' AND ord = 3 AND retired_at IS NULL AND text = $o$Delivered 10 decision-intelligence services on 4 query archetypes to production for ~10,000 patients, absorbing 20 review findings into one design$o$;
UPDATE resume_blocks SET html = $h$Drove agentic development on Claude Code and OpenAI Codex across a <strong>20-engineer team</strong>, codifying repository standards in CLAUDE.md and AGENTS.md files to shorten onboarding$h$ WHERE doc_key = 'seat:zenvyra-technical-co-founder' AND section_id = 'quick-vp' AND ord = 23 AND retired_at IS NULL AND text = $o$Drove a Claude Code and OpenAI Codex rollout across a 20-engineer team, codifying repository standards in CLAUDE.md and AGENTS.md files to shorten onboarding$o$;
UPDATE resume_blocks SET html = $h$Co-founded VoltusWave, releasing a no-code application Platform-as-a-Service (aPaaS) for web and Android where clients built apps like leave management; won <strong>8 early enterprise clients</strong>$h$ WHERE doc_key = 'seat:zenvyra-technical-co-founder' AND section_id = 'quick-voltuswave-cofounder' AND ord = 1 AND retired_at IS NULL AND text = $o$Co-founded VoltusWave and released its first no-code application Platform-as-a-Service (aPaaS) for web and Android on Amazon Elastic Container Service, winning 8 early enterprise clients$o$;
UPDATE resume_blocks SET html = $h$Codified a MuleSoft enterprise service bus scatter-gather integrating <strong>~30 supplier APIs</strong> in parallel, superseding .NET 2.0 code a prior team could not upgrade$h$ WHERE doc_key = 'seat:zenvyra-technical-co-founder' AND section_id = 'quick-teletext' AND ord = 1 AND retired_at IS NULL AND text = $o$Codified a MuleSoft enterprise service bus scatter-gather giving sales reps ~30 suppliers' rates in parallel, superseding .NET 2.0 code a prior team could not upgrade$o$;
UPDATE resume_blocks SET html = $h$Mechanised hotel-mapping reconciliation as an automated Amazon Web Services (AWS) Lambda workflow with human approval retained, growing revenue <strong>8% month over month</strong>$h$ WHERE doc_key = 'seat:zenvyra-technical-co-founder' AND section_id = 'quick-teletext' AND ord = 5 AND retired_at IS NULL AND text = $o$Mechanised the reconciliation pipeline on Amazon Web Services (AWS) Lambda with human approval retained, growing revenue 8% month over month$o$;
COMMIT;
