-- Adjudicated résumé edits for seat:epiq-lead-software-engineer (29 Sep 2026); each UPDATE matches the master text, so a re-run changes nothing.
\set ON_ERROR_STOP on
BEGIN;
UPDATE resume_blocks SET html = $h$Tuned <strong>hybrid precedent retrieval</strong> — structured filters plus Elasticsearch dense_vector search on self-hosted Amazon SageMaker embeddings — designed against an evaluation contract specifying <strong>100+ golden queries</strong>$h$ WHERE doc_key = 'seat:epiq-lead-software-engineer' AND section_id = 'quick-vp' AND ord = 8 AND retired_at IS NULL AND text = $o$Tuned precedent retrieval on Elasticsearch dense_vector search with self-hosted Amazon SageMaker embedders, designed against warm-path P99 under 200 ms and 0.75 normalised discounted cumulative gain$o$;
UPDATE resume_blocks SET html = $h$Assembled a <strong>10-query</strong> decision-intelligence platform in <strong>Python (FastAPI, LangChain, LangGraph)</strong> on <strong>4 reusable archetypes</strong> — Retrieval, Cohort Aggregation, Sequence Mining, Graph Traversal$h$ WHERE doc_key = 'seat:epiq-lead-software-engineer' AND section_id = 'quick-vp' AND ord = 10 AND retired_at IS NULL AND text = $o$Assembled a 10-query decision-intelligence platform on 4 reusable archetypes — Retrieval, Cohort Aggregation, Sequence Mining, Graph Traversal — on Amazon Neptune$o$;
UPDATE resume_blocks SET html = $h$Secured protected health information inside the client virtual private cloud, self-hosting embeddings, <strong>Llama 3.1</strong> for every model call, and <strong>LangSmith tracing</strong>$h$ WHERE doc_key = 'seat:epiq-lead-software-engineer' AND section_id = 'quick-vp' AND ord = 13 AND retired_at IS NULL AND text = $o$Secured protected health information inside the client virtual private cloud by self-hosting embeddings and Llama 3.1 for every model call$o$;
UPDATE resume_blocks SET html = $h$Extracted cross-domain patient cohorts through a deterministic <strong>multi-agent LangGraph</strong> state graph — <strong>3</strong> blind parallel finder agents behind a barrier that rejects hallucinated candidates$h$ WHERE doc_key = 'seat:epiq-lead-software-engineer' AND section_id = 'quick-vp' AND ord = 17 AND retired_at IS NULL AND text = $o$Extracted confounder-gated cohort comparisons behind propensity matching and standardised mean difference balance checks, making an unbalanced headline unrepresentable in the output type$o$;
UPDATE resume_blocks SET html = $h$Strengthened language-model access behind one <strong>LangChain provider seam</strong> over <strong>4</strong> back ends — mock, Anthropic, OpenAI, Ollama — so continuous integration exercises the exact production call path$h$ WHERE doc_key = 'seat:epiq-lead-software-engineer' AND section_id = 'quick-vp' AND ord = 18 AND retired_at IS NULL AND text = $o$Strengthened statistical rigour across 6 production pipelines with B=2000 bootstrap resamples and a Rosenbaum γ plus E-value sensitivity battery, keyed by shared match_manifest_id$o$;
UPDATE resume_blocks SET html = $h$Codified the <strong>scatter-gather</strong> integration pattern across <strong>25 hotel suppliers</strong> on MuleSoft's enterprise service bus, superseding a .NET 2.0 stack a prior team could not upgrade$h$ WHERE doc_key = 'seat:epiq-lead-software-engineer' AND section_id = 'quick-teletext' AND ord = 1 AND retired_at IS NULL AND text = $o$Codified a parallel scatter-gather across 25 hotel suppliers on a MuleSoft enterprise service bus, superseding a .NET 2.0 stack a prior team could not upgrade$o$;
COMMIT;
