-- Adjudicated résumé edits for seat:sahaj-principal-engineer (29 Sep 2026); each UPDATE matches the master text, so a re-run changes nothing.
\set ON_ERROR_STOP on
BEGIN;
UPDATE resume_blocks SET html = $h$Assembled a <strong>10-query</strong> decision-intelligence platform in <strong>Python (FastAPI, LangChain, LangGraph)</strong> on <strong>4 reusable archetypes</strong> — Retrieval, Cohort Aggregation, Sequence Mining, Graph Traversal$h$ WHERE doc_key = 'seat:sahaj-principal-engineer' AND section_id = 'quick-vp' AND ord = 10 AND retired_at IS NULL AND text = $o$Assembled a 10-query decision-intelligence platform on 4 reusable archetypes — Retrieval, Cohort Aggregation, Sequence Mining, Graph Traversal — on Amazon Neptune$o$;
UPDATE resume_blocks SET html = $h$Instituted event sourcing on <strong>DynamoDB single-table</strong> design, hydrating <strong>9–10 years of patient history</strong>, with a deterministic <strong>Parquet</strong> exporter checked by <strong>byte-for-byte</strong> golden-replay regression$h$ WHERE doc_key = 'seat:sahaj-principal-engineer' AND section_id = 'quick-vp' AND ord = 11 AND retired_at IS NULL AND text = $o$Instituted event sourcing on DynamoDB single-table design with a deterministic Parquet snapshot exporter and correction-event backbone, targeting P95 under 5 minutes for dependency-targeted slice rebuilds$o$;
UPDATE resume_blocks SET html = $h$Drove a <strong>Claude Code and OpenAI Codex</strong> rollout across a <strong>20-engineer</strong> team, covering daily design exploration, first-cut implementation and test scaffolding under <strong>hands-on review</strong>$h$ WHERE doc_key = 'seat:sahaj-principal-engineer' AND section_id = 'quick-vp' AND ord = 24 AND retired_at IS NULL AND text = $o$Drove a measured Claude Code and OpenAI Codex rollout across a 20-engineer team, covering daily design exploration, first-cut implementation and test scaffolding under review$o$;
UPDATE resume_blocks SET html = $h$Implemented multi-tenant isolation for <strong>280 axe Monitor clients</strong> — organisation identifier on every table, tenant from the <strong>JSON Web Token (JWT)</strong>, guarded by <strong>automated tests</strong>$h$ WHERE doc_key = 'seat:sahaj-principal-engineer' AND section_id = 'quick-deque' AND ord = 1 AND retired_at IS NULL AND text = $o$Implemented multi-tenant isolation across 280 axe Monitor clients, adding an organisation identifier to every table and resolving tenant from the JSON Web Token (JWT)$o$;
UPDATE resume_blocks SET html = $h$Championed decomposition of a monolith into <strong>10–15 services</strong> on one rule: a service earns its own process to scale independently or own its data$h$ WHERE doc_key = 'seat:sahaj-principal-engineer' AND section_id = 'quick-deque' AND ord = 7 AND retired_at IS NULL AND text = $o$Championed decomposition of a monolith into 10–15 services, splitting on independent scaling and database ownership rather than on team boundaries$o$;
UPDATE resume_blocks SET html = $h$Anchored decomposition of the <strong>IBM Db2 Configuration Manager</strong> monolith into <strong>Java and Spring Boot</strong> microservices across <strong>z/OS mainframe</strong> and distributed platforms, with no customer-visible impact$h$ WHERE doc_key = 'seat:sahaj-principal-engineer' AND section_id = 'quick-rocket' AND ord = 1 AND retired_at IS NULL AND text = $o$Anchored decomposition of the IBM Db2 Configuration Manager monolith into Java and Spring Boot microservices, defining boundaries across z/OS mainframe and distributed platforms$o$;
COMMIT;
